#cloud-config
merge_how: dict(recurse_array)+list(append)
write_files:
  - path: /var/lattice/setup/lattice-environment
    owner: "root:root"
    permissions: "0644"
    content: |
      CONSUL_SERVER_IP=$COORDINATOR_IP
      LATTICE_CELL_ID=cell-$ID
      GARDEN_EXTERNAL_IP=$CELL_IP